#pragma once

#include "TokenType.h"

const std::unordered_map<std::string, TokenType> specialWords = {
    {         "true",         TRUE_LITERAL },
    {        "false",        FALSE_LITERAL },
    {        "break",           BREAK_KEYW },
    {     "continue",        CONTINUE_KEYW },
    {          "for",             FOR_KEYW },
    {           "do",              DO_KEYW },
    {        "while",           WHILE_KEYW },
    {          "int",        INT_TYPE_RESW },
    {       "double",     DOUBLE_TYPE_RESW },
    {        "float",      FLOAT_TYPE_RESW },
    {         "char",       CHAR_TYPE_RESW },
    {       "string",     STRING_TYPE_RESW },
    {         "void",       VOID_TYPE_RESW },
    {         "bool",       BOOL_TYPE_RESW },
    {       "struct",     STRUCT_TYPE_RESW },
    {         "enum",            ENUM_RESW },
    {        "const",           CONST_RESW },
    {       "static",          STATIC_RESW },
    {     "unsigned",        UNSIGNED_RESW },
    {       "return",          RETURN_RESW },
    {           "if",              IF_RESW },
    {         "else",            ELSE_RESW },
    {         "elif",            ELIF_RESW },
    {      "Machine",    MACHINE_TYPE_RESW },
    {     "@context",     MAC_CONTEXT_RESW },
    {       "@final",       MAC_FINAL_RESW },
    {  "@finalState", MAC_FINAL_STATE_RESW },
    {       "@start",       MAC_START_RESW },
    {       "@state",       MAC_STATE_RESW },
    {      "@states",      MAC_STATES_RESW },
    { "@transitions", MAC_TRANSITIONS_RESW },
};
